### ISSUE TITLE
requests is recommended

### ISSUE THREAD

**Issue by KIDJourney** [upclinux/DrUPC#1]
http://docs.python-requests.org/en/latest/

**Comment by ghost** [comment]
说点和Issue本身无关但是还有点关系的话题：
1. 由于校园网认证只需要打开浏览器填一下学号和密码，所以这段脚本实际上是为开发板准备的。一旦将来社团举办户外活动，不方便组建局域网的时候（可通过串口控制但是无法使用图形界面）可以用这段脚本偷个懒。
2. 仅仅是偷个懒，因为装个w3m或lynx，虽然是纯文本浏览器，同样能完成认证。
3. 大家应该都知道那个“强”智教务系统只支持IE吧，对于Linux/OS X用户来说，来个爬虫太有必要了。但是搞成Server吧还容易被查水表，所以弄成Client更安全一些。我倒是[写过](https://github.com/vjudge1/upccrawler)，本来打算对外提供接口，不过我感觉自己写得很恶心。有机会用Python和requests改写一遍。

**Comment by KIDJourney** [comment]
Orz...
我写的登录就发了两个request，没有分网络情况也完全没有考虑无法登陆。
